Add support for using curl to download podcasts.

diff --git a/bashpodder b/bashpodder
--- a/bashpodder
+++ b/bashpodder
@@ -11,13 +11,33 @@
 cd $(dirname $0)
 
 # datadir is the directory you want podcasts saved to:
-datadir=$(date +%Y-%m-%d)
+#datadir=$(date +%Y-%m-%d)
+datadir="bptest"
+
+# Number of times to retry a download
+download_retries=10
+
+# Which downloader to use? Supported options are 'curl' and 'wget'
+downloader='wget'
 
 # create datadir if necessary:
 mkdir -p $datadir
 
 # Delete any temp file:
 rm -f temp.log
+
+# Support both curl and wget
+case $downloader in
+	wget)
+		download_cmd="wget -U BashPodder -c -q -t $download_retries -O "
+	;;
+	curl)
+		download_cmd="curl -A BashPodder -s --retry $download_retries -o "
+	;;
+	*)
+		echo "Downloader $downloader not supported."
+	exit 1
+esac
 
 # Read the bp.conf file and wget any url not already in the podcast.log file:
 while read podcast
@@ -28,7 +48,7 @@ while read podcast
 		echo $url >> temp.log
 		if ! grep "$url" podcast.log > /dev/null
 			then
-			wget -t 10 -U BashPodder -c -q -O $datadir/$(echo "$url" | awk -F'/' {'print $NF'} | awk -F'=' {'print $NF'} | awk -F'?' {'print $1'}) "$url"
+				$download_cmd $datadir/$(echo "$url" | awk -F'/' {'print $NF'} | awk -F'=' {'print $NF'} | awk -F'?' {'print $1'}) "$url"
 		fi
 		done
 	done < bp.conf
